[package]
name = "btf-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
btf-rs = { path = "../btf-rs", features = ["fuzzing", "regex"] }
libfuzzer-sys = "0.4"
memmap2 = "0.9"
regex = "1.12"

[[bin]]
name = "btf_api"
path = "fuzz_targets/btf_api.rs"
test = false
doc = false
bench = false

[[bin]]
name = "btf_section"
path = "fuzz_targets/btf_section.rs"
test = false
doc = false
bench = false

[[bin]]
name = "types"
path = "fuzz_targets/types.rs"
test = false
doc = false
bench = false
